=== tania15/XML-programming/Project/Pastry shop.dtd
<!ELEMENT catalog (cakes, candies, cookies, creams)>

<!ELEMENT cakes (cake)+>
<!ELEMENT cake (name, category, price, available, piece, weight, products,
                expiryDate, storage, description, image)>
<!ATTLIST cake id NMTOKEN #REQUIRED>                   
<!ELEMENT name (#PCDATA)>
<!ELEMENT category EMPTY>
<!ATTLIST category type NMTOKEN #REQUIRED>   
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA #FIXED 'Лев'>         
<!ELEMENT available (#PCDATA)>
<!ELEMENT piece (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ATTLIST weight weight CDATA #FIXED 'кг'>               
<!ELEMENT products (product)+>
<!ELEMENT product (#PCDATA)>
<!ATTLIST product number NMTOKEN #REQUIRED>
<!ELEMENT expiryDate (#PCDATA)>
<!ATTLIST expiryDate date CDATA #FIXED 'Дни'>     
<!ELEMENT storage (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>

<!ELEMENT candies (candy)*>
<!ELEMENT candy (name,price,expiryDate)>

<!ELEMENT cookies (cookie)*>
<!ELEMENT cookie (name,price,quantity,products)>
<!ELEMENT quantity (#PCDATA)>
<!ATTLIST quantity quantity NMTOKEN #REQUIRED>

<!ELEMENT creams (cream)*>
<!ELEMENT cream (type,price,quantity)>
<!ELEMENT type (#PCDATA)>

=== tania15/XML-programming/Project/Pastry shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "Pastry shop.dtd">

<!-- PASTRY SHOP -->

<catalog>
    <cakes>
        <cake id = 'C1'>                      
            <name>Мираж</name>
            <category type = 'Шоколадова'/>
            <price currency = 'Лев'>28</price>
            <available>2</available>
            <piece>16</piece>
            <weight weight = 'кг'>1.8</weight>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P14'>Вода</product>
                <product number = 'P6'>Прясно мляко</product>
                <product number = 'P36'>Натурален шоколад</product>
            </products>   
            <expiryDate date = 'Дни'>10</expiryDate>   
            <storage>В хладилник</storage>
            <description><![CDATA[ 
                Шоколадова сметана с какаови платки, обвити в плътен течен шоколад.  
                ]]>
            </description> 
            <image>http://www.chochko.com/shop/стандартни/торта-мираж/</image>
        </cake>  
        
        <cake id = 'C4'>
            <name>Еклерова</name>
            <category type = 'Млечна'/>   
            <price currency = 'Лев'>32</price>
            <available>1</available>
            <piece>16</piece>
            <weight weight = 'кг'>2.1</weight>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P14'>Вода</product>
                <product number = 'P6'>Прясно мляко</product>
                <product number = 'P61'>Сметана</product>
                <product number = 'P37'>Млечен шоколад</product>
                <product number = 'P107'>Фъстъци</product>
            </products>   
            <expiryDate date = 'Дни'>8</expiryDate>   
            <storage>В хладилник</storage>
            <description><![CDATA[ 
                Ароматно изкушение от млечен крем с мини еклери и млечен шоколад, 
                бели пандишпанови платки, украсена с бял шоколад и парченца фъстъци.  
                ]]>
            </description> 
            <image>http://www.chochko.com/shop/стандартни/торта-еклерова-2/</image>
        </cake>    
    </cakes>
    
    <candies>
        <candy>
            <name>Трюфел</name>
            <price currency = 'Лев'>11.20</price>
            <expiryDate date = 'Дни'>20</expiryDate>
        </candy>
        
        <candy>
            <name>Кокосови бонбони</name>
            <price currency = 'Лев'>9.90</price>
            <expiryDate date = 'Дни'>20</expiryDate>
        </candy>
    </candies>  
    
    <cookies>
        <cookie>
            <name>Ореховки</name>
            <price currency = 'Лев'>1.10</price>
            <quantity quantity = 'Брой'>1</quantity>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P113'>Орехи</product>
            </products>  
        </cookie>
        
        <cookie>
            <name>Пълнозърнести бисквити</name>
            <price currency = 'Лев'>1.40</price>
            <quantity quantity = 'Брой'>1</quantity>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P8'>Пълнозърнесто брашно</product>
                <product number = 'P114'>Бадеми</product>
                <product number = 'P129'>Тиквени семки</product>
                <product number = 'P147'>Сусам</product>
                <product number = 'P151'>Ленено семе</product>
            </products>  
        </cookie>
    </cookies>
    
    <creams>
        <cream>
            <type>Шоколадов</type>
            <price currency = 'Лев'>3</price>
            <quantity quantity = 'Мл'>250</quantity>
        </cream>
        
        <cream>
            <type>Яйчен</type>
            <price currency = 'Лев'>2.80</price>
            <quantity quantity = 'Мл'>220</quantity>
        </cream>
    </creams>
    
</catalog>

=== tania15/XML-programming/Project/Pastry shop 3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "Pastry shop.dtd">

<catalog>
    <cakes>
        <cake id = 'C2'>                      
            <name>Шоко лешник</name>
            <category type = 'Шоколадова'/>
            <price currency = 'Лев'>31.50</price>
            <available>2</available>
            <piece>16</piece>
            <weight weight = 'кг'>2.300</weight>
            <products>           
                <product number = 'P1'>Захар</product>  
                <product number = 'P2'>Пудра захар</product>
                <product number = 'P7'>Брашно</product>
                <product number = 'P6'>Прясно мляко</product>
                <product number = 'P14'>Вода</product>
                <product number = 'P61'>Какао</product>
                <product number = 'P36'>Натурален шоколад</product>
                <product number = 'P115'>Лешник</product>
            </products>   
            <expiryDate date = 'Дни'>10</expiryDate>   
            <storage>В хладилник</storage>
            <description><![CDATA[ 
                Нежно съчетание на лешников какаов крем, кафеви платки и цели шоколадени лешници.  
                ]]>
            </description> 
            <image>http://www.chochko.com/shop/стандартни/шоко-лешник/</image>
        </cake>  
        
        <cake id = 'C3'>
            <name>Гараш</name>
            <category type = 'Шоколадова'/>   
            <price currency = 'Лев'>34</price>
            <available>1</available>
            <piece>16</piece>
            <weight weight = 'кг'>1.900</weight>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P14'>Вода</product>
                <product number = 'P6'>Прясно мляко</product>
                <product number = 'P36'>Натурален шоколад</product>
                <product number = 'P37'>Млечен шоколад</product>
                <product number = 'P113'>Орехи</product>
            </products>   
            <expiryDate date = 'Дни'>10</expiryDate>   
            <storage>В хладилник</storage>
            <description><![CDATA[ 
                Прекрасно съчетание от шоколадов крем гараш с орехови ядки, 
                орехови платки, покрита с великолепен натурален шоколад.  
                ]]>
            </description> 
            <image>http://www.chochko.com/shop/стандартни/торта-гараш/</image>
        </cake>  
        
    </cakes>
    
    <candies></candies>  
    
    <cookies>
        <cookie>
            <name>Шоколадиви бишкоти</name>
            <price currency = 'Лев'>3.30</price>
            <quantity quantity = 'Брой'>6</quantity>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P37'>Млечен шоколад</product>
                <product number = 'P6'>Прясно мляко</product>
            </products>  
        </cookie>
        
        <cookie>
            <name>Курабии</name>
            <price currency = 'Лев'>2.80</price>
            <quantity quantity = 'Брой'>15</quantity>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P18'>Олио</product>
                <product number = 'P7'>Брашно</product>
                <product number = 'P16'>Кисело мляко</product>
                <product number = 'P143'>Бакпулвер</product>
                <product number = 'P201'>Ванилия</product>
            </products>  
        </cookie>
    </cookies>
    
    <creams>
        <cream>
            <type>Ягодов мус</type>
            <price currency = 'Лев'>3.90</price>
            <quantity quantity = 'Мл'>220</quantity>
        </cream>
    </creams>
    
</catalog>

=== tania15/XML-programming/Project/Pastry shop 2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "Pastry shop.dtd">

<catalog>
    <cakes>
        <cake id = 'C12'>                      
            <name>Черно и бяло</name>
            <category type = 'Класическа'/>
            <price currency = 'Лев'>29.50</price>
            <available>1</available>
            <piece>16</piece>
            <weight weight = 'кг'>2.050</weight>
            <products>           
                <product number = 'P1'>Захар</product>  
                <product number = 'P2'>Пудра захар</product>
                <product number = 'P7'>Брашно</product>
                <product number = 'P14'>Вода</product>
                <product number = 'P11'>Кисело мляко</product>
                <product number = 'P61'>Какао</product>
                <product number = 'P457'>Ром с аромат на шоколад</product>
                <product number = 'P558'>Френски макарон</product>
                <product number = 'P201'>Ванилия</product>
            </products>   
            <expiryDate date = 'Дни'>10</expiryDate>   
            <storage>В хладилник</storage>
            <description><![CDATA[ 
                Торта с класически вкус на крем ванилия и шоколад. Какаови блатове 
                напръскани с ароматен ром, полята с шоколад и украсена с хрупкав 
                френски макарон.  
                ]]>
            </description> 
            <image>http://www.chochko.com/shop/стандартни/черно-и-бяло/</image>
        </cake>  
        
        <cake id = 'C31'>
            <name>Рафаело</name>
            <category type = 'Стандартна'/>   
            <price currency = 'Лев'>35</price>
            <available>1</available>
            <piece>16</piece>
            <weight weight = 'кг'>2.250</weight>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P5'>Яйца</product>
                <product number = 'P14'>Вода</product>
                <product number = 'P6'>Прясно мляко</product>
                <product number = 'P62'>Подсладена сладкарска сметана</product>
                <product number = 'P38'>Бял шоколад</product>
                <product number = 'P103'>Кокосови стърготини</product>
                <product number = 'P114'>Бадеми</product>
            </products>   
            <expiryDate date = 'Дни'>11</expiryDate>   
            <storage>В хладилник</storage>
            <description><![CDATA[ 
                Класическа комбинация на кокосови блатове с крем рафаело, обсипани с фин кокос.  
                ]]>
            </description> 
            <image>http://www.chochko.com/shop/стандартни/торта-рафаело/</image>
        </cake>  
        
        <cake id = 'C6'>
            <name>Плодова</name>
            <category type = 'Класическа'/>   
            <price currency = 'Лев'>18</price>
            <available>3</available>
            <piece>8</piece>
            <weight weight = 'кг'>1.150</weight>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P5'>Яйца</product>
                <product number = 'P14'>Вода</product>
                <product number = 'P6'>Прясно мляко</product>
                <product number = 'P62'>Подсладена сладкарска сметана</product>
                <product number = 'P310'>Ягода</product>
                <product number = 'P318'>Портокол</product>
                <product number = 'P320'>Киви</product>
                <product number = 'P304'>Ябълка</product>
            </products>   
            <expiryDate date = 'Дни'>12</expiryDate>   
            <storage>В хладилник</storage>
            <description><![CDATA[ 
                Домашен млечен крем ухаещ на вашето детство, бели пандишпанови 
                платки украсена с разнообразни плодове.  
                ]]>
            </description> 
            <image>http://www.chochko.com/shop/стандартни/плодова-пита/</image>
        </cake>    
    </cakes>
    
    <candies>
        <candy>
            <name>Трюфел</name>
            <price currency = 'Лев'>11.20</price>
            <expiryDate date = 'Дни'>20</expiryDate>
        </candy>
        
        <candy>
            <name>Кокосови бонбони</name>
            <price currency = 'Лев'>9.90</price>
            <expiryDate date = 'Дни'>20</expiryDate>
        </candy>
    </candies>  
    
    <cookies>
        <cookie>
            <name>Меденка</name>
            <price currency = 'Лев'>0.90</price>
            <quantity quantity = 'Брой'>1</quantity>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P46'>Мед</product>
            </products>  
        </cookie>
        
        <cookie>
            <name>Бисквита с бял шоколад и лешници</name>
            <price currency = 'Лев'>1.25</price>
            <quantity quantity = 'Брой'>1</quantity>
            <products>           
                <product number = 'P1'>Захар</product>    
                <product number = 'P7'>Брашно</product>
                <product number = 'P38'>Бял шоколад</product>
                <product number = 'P115'>Лешник</product>
            </products>  
        </cookie>
    </cookies>
    
    <creams>
        <cream>
            <type>Тирамису</type>
            <price currency = 'Лев'>3.10</price>
            <quantity quantity = 'Мл'>250</quantity>
        </cream>
        
        <cream>
            <type>Крем карамел</type>
            <price currency = 'Лев'>2.80</price>
            <quantity quantity = 'Мл'>225</quantity>
        </cream>
        
        <cream>
            <type>Мус ванилия</type>
            <price currency = 'Лев'>2.95</price>
            <quantity quantity = 'Мл'>240</quantity>
        </cream>
    </creams>
    
</catalog>
